### ISSUE TITLE
minor fixes needed for ~/R/Raster-Data-In-R/

### ISSUE THREAD

**Issue by fluby** [lwasser/NEON-Data-Skills#14]
[ ] - correct San Joachim to San Joaquin
 [ ] - example output for 'DEM <- raster("DigitalTerrainModel/SJER2013_DTM.tif")' looks like it is actually for the DTMHill version of the file

**Comment by lwasser** [comment]
hey @fluby thanks!! fixed the spelling. 

Gosh the DTM worked out just fine for me. are the values between 0 and 1 when you import it? did you download the most recent version of the data (not that - that should matter) . i can look at it tomorrow but it seems ok to me in both R and QGIS. does it look like a hillshade to you because it's grey or because of the values? thanks for being on top of this!!

**Comment by fluby** [comment]
Apologies for the confusion, Leah! I just meant that this example output looks like it's for a different file than the example intended: 
class       : RasterLayer 
dimensions  : 5060, 4299, 21752940  (nrow, ncol, ncell)
resolution  : 1, 1  (x, y)
extent      : 254570, 258869, 4107302, 4112362  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : /Users/law/Documents/data/CHM_InSitu_Data/DigitalTerrainModel/SJER2013_DTMHill.tif 
names       : **SJER2013_DTMHill **
values      : 0, 253  (min, max)

**Comment by lwasser** [comment]
OOps. i totally missed that. great catch - thanks @fluby . fixed in commit:

https://github.com/lwasser/NEON-Data-Skills/commit/5d903e2cad6b851320ae2cc0d38f1a2a4749c1f3
Cheers! :)
