### ISSUE TITLE
Minor comments for Intro-To-HDF5-In-R

### ISSUE THREAD

**Issue by fluby** [lwasser/NEON-Data-Skills#32]
* correct rhfd5 in Goals/Objectives to rhdf5
* where do we find the D17_2013_vegStr.csv file referenced in the Challenge?

**Comment by lwasser** [comment]
hey i can adjust these. i just uploaded the veg str file

http://neondataskills.org/data/D17_2013_vegStr.zip

i'll add a link to it in the exercise and fix the above as well :) thanks for catching all of this!

**Comment by lwasser** [comment]
ok i see what happened. i have'nt fully transitioned the intro to HDF5 lesson to RMD. when you're done with your edits and you submit the PR, i'll go ahead and reformat the entire RMD to be the actual lesson content :) then i'll fix the above! :) thanks kate!

**Comment by natalie-robinson** [comment]
Hey @lwasser  - the last HDF5 figure in the 'about' lesson is kinda repetitive and I didn't really see what it was trying to illustrate. Just a thought.

Also - It is easy to miss downloading the hyperspectral data at the beginning of the viewer lesson, can you put that link in a big black box that matches the one for the sensor data?

**Comment by lwasser** [comment]
hey guys -- if we can keep issues separate that would be super awesome since i use each issue to track changes!  so if you find a new issue - please submit it as a new issue. 
I've added a link to the str data here via a green button:

http://neondataskills.org/coding-and-informatics/Intro-HDF5-R/

i've added a button for the second dataset in the viewer activity
http://neondataskills.org/HDF5/Exploring-Data-HDFView/

did i get everything? please let me know and i'll close this.
